### ISSUE TITLE
Cloning via SSH

### ISSUE THREAD

**Issue by BrizzleRocker** [hashicorp/homebrew-tap#102]
When trying to install the tap using `brew tap hasicorp/tap` I was prompted for my GitHub credentials. As I have already setup an SSH key the correct syntax is `brew tap hasicorp/tap https://github.com/hashicorp/homebrew-tap`.

Could the documentation / README please be updated to reflect this?

References: [Google](https://www.google.com/search?rlz=1C5CHFA_enGB823GB823&sxsrf=ALeKk03GDfbQofTo56zmsXIj9nRM1Ywapw%3A1610627093764&ei=FTgAYOqMLo-fgQaUhrmYCA&q=brew+tap+asks+for+github+username&oq=brew+tap+ask&gs_lcp=CgZwc3ktYWIQAxgAMgUIABDJAzoECAAQRzoECCMQJzoICAAQyQMQkQI6BQgAEJECOgQIABBDOgcIABCxAxBDOgsILhCxAxDHARCvAToFCAAQsQM6AggAOggILhDHARCvAToHCAAQFBCHAjoOCC4QxwEQrwEQyQMQkwI6BggAEBYQHlCRiQFY2JoBYKOmAWgAcAN4AIABfYgBqwiSAQM2LjaYAQCgAQGqAQdnd3Mtd2l6yAEIwAEB&sclient=psy-ab)

**Comment by BrizzleRocker** [comment]
Added https://github.com/hashicorp/homebrew-tap/pull/103

**Comment by kpenfound** [comment]
Merged!
