### ISSUE TITLE
#133 breaks tap for Apple Silicon installs

### ISSUE THREAD

**Issue by behe** [hashicorp/homebrew-tap#134]
#133 breaks tap for Apple Silicon installs since the hardware is not mac + intel.

```
brew readall
Error: Invalid formula: /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/consul.rb
formulae require at least a URL
Error: Invalid formula: /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/vault.rb
formulae require at least a URL
Error: Invalid formula: /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/terraform.rb
formulae require at least a URL
Error: Invalid formula: /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/nomad.rb
formulae require at least a URL
Error: Invalid formula: /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/boundary.rb
formulae require at least a URL
```

**Comment by Arthegor** [comment]
Same problem ( Mac mini M1 8Go )
```
brew tap hashicorp/tap
==> Tapping hashicorp/tap
Cloning into '/opt/homebrew/Library/Taps/hashicorp/homebrew-tap'...
remote: Enumerating objects: 215, done.
remote: Counting objects: 100% (215/215), done.
remote: Compressing objects: 100% (132/132), done.
remote: Total 1027 (delta 117), reused 171 (delta 83), pack-reused 812
Receiving objects: 100% (1027/1027), 202.59 KiB | 2.11 MiB/s, done.
Resolving deltas: 100% (537/537), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/consul.rb
formulae require at least a URL
Error: Invalid formula: /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/vault.rb
formulae require at least a URL
Error: Invalid formula: /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/terraform.rb
formulae require at least a URL
Error: Invalid formula: /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/nomad.rb
formulae require at least a URL
Error: Invalid formula: /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/boundary.rb
formulae require at least a URL
Error: Cannot tap hashicorp/tap: invalid syntax in tap!
```

**Comment by radeksimko** [comment]
Thank you for the report.

AFAICT none of the mentioned products have released compatible (darwin/arm64) builds yet:

 - https://releases.hashicorp.com/boundary/0.1.8/
 - https://releases.hashicorp.com/consul/1.10.0-alpha/
 - https://releases.hashicorp.com/nomad/1.0.4/
 - https://releases.hashicorp.com/terraform/0.15.0-rc1/
 - https://releases.hashicorp.com/vault/1.7.0/

So it would make sense for _installation_ of any of these formulas to fail.

However you are right that _tapping_ should work without any failures.

I think we just need to find a way of communicating the (limited) compatibility in a graceful way. I remember Homebrew used to have a stanza for declaring OS version compatibility - will try to find it and see if we can patch the formula generator.

**Comment by behe** [comment]
I've been using https://releases.hashicorp.com/vault/1.6.3/ on Apple Silicon under Rosetta 2 without problem. Maybe just remove the intel check on mac systems?

**Comment by radeksimko** [comment]
Based on some [(brief) docs](https://github.com/Homebrew/homebrew-cask/blob/cd03f5f3d6d440cf9e0610c3c4fbc58ddb464617/doc/cask_language_reference/stanzas/depends_on.md#depends_on-arch) available and spelunking in the Homebrew source code I think something like this should work:

```ruby
depends_on arch: [:x86_64] if OS.mac?
```
or alternatively
```ruby
on_macos do
  depends_on arch: [:x86_64]
end
```

However this should probably be inserted only if the formula (product version) being created really _doesn't_ support that architecture. [It seems](https://github.com/hashicorp/homebrew-tap/blob/master/util/lambda_trigger/lambda_trigger.go) that we do not ingest list of builds or supported OS/architectures on release - but I will let @kpenfound weigh in here as he has far more context.

@behe This tap purposefully adheres to the support that the maintaining product teams communicate (unlike the core tap). AFAIK the maintaining teams have yet to test these products under Apple Silicon thoroughly (whether under Rosetta or natively) before committing to supporting it officially.

**Comment by kpenfound** [comment]
Thanks for jumping in @radeksimko , that makes sense. We can add some branching logic to the templating until we have darwin_arm64 support across the board. I'll dig into this today.
