### ISSUE TITLE
Vagrant not found

### ISSUE THREAD

**Issue by zatch95** [hashicorp/homebrew-tap#151]
Hi! 

I'm trying to get Vagrant installed, when I run 'brew install vagrant' I get 
<img width="492" alt="Screenshot 2021-07-15 at 14 11 15" src="https://user-images.githubusercontent.com/87482656/125793709-9f35dba5-5098-4455-83e0-bc950a69d543.png">
 
Vagrant-completion doesn't do the trick either, any help would be great!

cheers

**Comment by kpenfound** [comment]
Hi @zatch95 , what's your `brew --version`? When I `brew search vagrant` I can see it available as a cask, but I think in older versions of homebrew you'd need to `brew cask install vagrant` for that to work

**Comment by mdeggies** [comment]
Marking as closed for now. Please feel free to reach back out if you run into any further issues.
