### ISSUE TITLE
Terraform 1.3.2

### ISSUE THREAD

**Issue by theherk** [hashicorp/homebrew-tap#188]
I noticed the latest terraform release 1.3.2 is available in the community tap, but not here. I was going to fork and add, but I realized hc-espd-packager does most of this work. So I wonder, what triggers releases making it into your managed tap?

**Comment by mdeggies** [comment]
Thanks for the report! Fixed in https://github.com/hashicorp/homebrew-tap/commit/c0f9df68afacc6bfa34d049aa3bc768833d768c7
