### ISSUE TITLE
Calling plist_options is deprecated

### ISSUE THREAD

**Issue by corbishley** [hashicorp/homebrew-tap#201]
got the following message when calling `brew doctor`
```
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the hashicorp/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/hashicorp/homebrew-tap/Formula/vault.rb:37
```

**Comment by erickestefano** [comment]
hi, i have the same problem, some suggestions?

**Comment by sramekmichal** [comment]
Same problem here

**Comment by dronenb** [comment]
Note there's an [open PR](https://github.com/hashicorp/homebrew-tap/pull/203) addressing this issue.

**Comment by msiege2** [comment]
> Note there's an [open PR](https://github.com/hashicorp/homebrew-tap/pull/203) addressing this issue.

That PR only fixes vault.  Would also need for other products (consul, nomad) as well as enterprise versions.

**Comment by jlucktay** [comment]
I've just put in [a PR](https://github.com/hashicorp/homebrew-tap/pull/204) to update the code that generates the formulas, as well as updating the formulas themselves.
Hope this helps!

**Comment by juliosaraiva** [comment]
> I've just put in [a PR](https://github.com/hashicorp/homebrew-tap/pull/204) to update the code that generates the formulas, as well as updating the formulas themselves. Hope this helps!

Merge it urgent please!
