### ISSUE TITLE
Terraform 1.5.0 release

### ISSUE THREAD

**Issue by benlangfeld** [hashicorp/homebrew-tap#241]
It looks like Terraform 1.5.0 was released today. Could we get the tap updated to reflect that? I thought it was automated but doesn't seem to have happened this time.

**Comment by sarahethompson** [comment]
Thanks @benlangfeld, this should be updated now.

**Comment by benlangfeld** [comment]
Thanks :)

**Comment by benlangfeld** [comment]
@sarahethompson It looks like the bot might be broken again, 1.5.3 was not made available even though it was released 5 days ago.

**Comment by sarahethompson** [comment]
Hi @benlangfeld sorry I missed your ping. This was updated on July 19th, and you should see Terraform 1.5.4 in there now too (released 2 days ago). Apologies for the delay!
