### ISSUE TITLE
Add Sentinel to Tap

### ISSUE THREAD

**Issue by jeffsanicola** [hashicorp/homebrew-tap#52]
I use the Sentinel CLI for policy testing and development and it would be nice if the binary was available via Brew like the rest of the HashiCorp products.

**Comment by kpenfound** [comment]
Hi @jeffsanicola ,

Thank you for the suggestion! We intend on adding this as soon as we can.  I'll try to provide updates as we know more!

**Comment by cam-stitt** [comment]
I've added a PR with the formula in #141. I'm not sure if there are other required tasks?

**Comment by kpenfound** [comment]
PR #141 Merged!
