### ISSUE TITLE
Add support for enterprise binaries

### ISSUE THREAD

**Issue by ykhemani** [hashicorp/homebrew-tap#55]
Hi!

Could we add support for enterprise binaries?

Thanks!

**Comment by ykhemani** [comment]
Please see [PR # 56](https://github.com/hashicorp/homebrew-tap/pull/56), and let me know if that looks okay. Thanks!

**Comment by mdeggies** [comment]
Thanks for your note! This went out in https://github.com/hashicorp/homebrew-tap/pull/181. Let us know if you have any issues.
