### ISSUE TITLE
multiple versions

### ISSUE THREAD

**Issue by FernandoMiguel** [hashicorp/homebrew-tap#57]
Community formula supports multiple versions in the format of @_version_
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/terraform@0.12.rb

the apt repo also supports multiple versions

**Comment by kpenfound** [comment]
Hi @FernandoMiguel ,

Our intent with this tap is to provide the latest versions for Hashicorp products.  Unfortunately, brew does not gracefully handle versioning like a package manager such as apt does.

To manage multiple versions of terraform, or non-latest versions, we recommend tools such as [tfenv](https://github.com/tfutils/tfenv).

**Comment by FernandoMiguel** [comment]
That's why I'm asking for multiple formulas.
One per supported version
Just like community does

**Comment by cotarg** [comment]
Hi @FernandoMiguel:

I'd like to follow up for a bit of clarity here.

The original use case this was designed to target is that of a developer who needs to set up their working environment and who wants to get the most recent version of our tools, or who wants to keep their tools in sync with our official releases. Homebrew does not manage versioning gracefully, requiring maintaining individual formulae for each version (as noted). This is currently an out of scope feature for reasons of pragmatism though we may consider it again in the future.
