### ISSUE TITLE
Add Linux support

### ISSUE THREAD

**Issue by rothgar** [hashicorp/homebrew-tap#59]
The README says these formula will work with Linux but the formula themselves only download the macOS binaries.

Can we get Linux support too please?

I'm happy to help make it work if someone can point me to the repos/CI that generates the formula files.

**Comment by kpenfound** [comment]
Hi @rothgar ,

Our current focus with the tap is macOS distribution, and we recommend the [official Hashicorp linux repository](https://www.hashicorp.com/blog/announcing-the-hashicorp-linux-repository) for managing linux installations.

We're planning on updating the README with more clarity around this as well as contribution help/navigation (such as: the formula updating happens from the github workflow on this repo).

I'm going to close this for now, but as we see demand for linux support in homebrew we'll revisit!

**Comment by kpenfound** [comment]
Reopening this as a discussion place for Linux support. Also see discussion here: https://github.com/hashicorp/homebrew-tap/pull/70

**Comment by rothgar** [comment]
Happy to help or provide examples of releases in other OSS projects I've worked on with brew

**Comment by cotarg** [comment]
Just as a quick update since it was mentioned on the linked PR, it does look like we're pursuing a `goreleaser` strategy and iterating our tap a bit. I don't have a predicted timeline yet, but wanted to confirm we're looking at how to fit this into the roadmap this winter!

**Comment by rothgar** [comment]
Thanks for the update! Also good to mention goreleaser/goreleaser#1903 which will allow support for Arm based Macs once go supports it with 1.16 release.
